/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Egirinnigirinn (https://sketchfab.com/Egirinnigirinn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-rust-lang-on-mini-cpu-0fd83952df3d459889482cb7ec53660c
Title: The Rust lang on mini CPU
*/

import {Float, useGLTF} from '@react-three/drei'

export function RustLogo(props) {
    const {nodes, materials} = useGLTF('models/the_rust_lang_on_mini_cpu.glb')
    return (
        <Float floatIntensity={1}>
            <group {...props} dispose={null}>
                <group
                    position={[0.482, 0.182, 0.003]}
                    rotation={[5, Math.PI, 20]}
                    scale={0.5}>
                    <mesh

                        geometry={nodes.Object_12.geometry}
                        material={materials['Material.004']}
                    />
                    <mesh

                        geometry={nodes.Object_13.geometry}
                        material={materials['Material.001']}
                    />
                    <mesh

                        geometry={nodes.Object_14.geometry}
                        material={materials['Material.005']}
                    />
                    <mesh

                        geometry={nodes.Object_15.geometry}
                        material={materials['Material.006']}
                    />
                </group>
            </group>
        </Float>
    )
}

export default RustLogo;
useGLTF.preload('models/the_rust_lang_on_mini_cpu.glb')